### ISSUE TITLE
Bug: `/entries/most-popular-tags` returns empty when offset is high

### ISSUE THREAD

**Issue by navid-kalaei** [slowtec/openfairdb#386] opened 2021-12-04 05:03 UTC
## Problem

At this time `/count/tags` returns `15739`. However when calling `entries/most-popular-tags?offset=15000`, returns an empty array.

## Expected Behaviour

To get tags from `15000` to `15739`

**Comment by wellemut** [comment] 2021-12-26 22:22
Correct, this call is empty: https://kartevonmorgen.org/api/v0/entries/most-popular-tags?min-count=1&offset=15000&limit=1000
In the tags-count https://kartevonmorgen.org/api/v0/count/tags it says 15975 tags (alternative url https://api.ofdb.io/v0/count/tags)

First call is working perfectly: https://api.ofdb.io/v0/entries/most-popular-tags?min-count=1&offset=0&limit=1000
Last working call is 14.000 entries, with just around 760 tags: https://api.ofdb.io/v0/entries/most-popular-tags?min-count=1&offset=14000&limit=1000

@navid-kalaei I guess the problem is not a broken URL but a misscommunication.
The 'tags-count' counts all tags that ever have been used.
But the 'most pupular tags' call only gives you tags that are currently used at least 1 time.
So we have around 15.975-14.760=1.215  tags which are not in use, and therefore not provided in the "most popular tags"

I will close this issue, as this is not a bug.

**Closed as completed by wellemut** 2021-12-26 22:22 UTC
Labels: bug
